### ISSUE TITLE
fakechroot-2.20.1-4.fc33 FTBFS: t/escape-nested-chroot.t fails

### ISSUE THREAD

**Issue by sergiomb2** [dex4er/fakechroot#77]
you might be interested 

https://bugzilla.redhat.com/show_bug.cgi?id=1838637
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964668

**Comment by sergiomb2** [comment]
t/escape-nested-chroot.t.log

1..8
ok 1 # SKIP not root
ok 2 # SKIP not root
ok 3 # SKIP not root
ok 4 # SKIP not root
ok 5 fakechroot test-chroot / / (not escaped): 28123421 / 28123421 /
ok 6 fakechroot test-chroot / . (not escaped): 28123421 / 28123421 /
ok 7 fakechroot test-chroot . / (not escaped): 28123421 / 28123421 /
not ok 8 fakechroot test-chroot . . (escaped): 28123421 / 28123421 /
FAIL t/escape-nested-chroot.t (exit status: 1)

**Comment by sergiomb2** [comment]
[f32.txt](https://github.com/dex4er/fakechroot/files/5120574/f32.txt)
[f33.txt](https://github.com/dex4er/fakechroot/files/5120575/f33.txt)

on Fedora 32 the test doesn't fail but fails on F33, above are the packages that are installed for F32 and F33 test , any clue what was the package update that change the test result ?

Thanks

**Comment by josch** [comment]
On debian, fakechroot started failing 2020-06-22 when coreutils was upgraded from 8.30-3+b1 to 8.32-1.

This makes sense, because of this coreutils commit which started using statx instead of stat: http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commit;h=a99ab266110795ed94a9cb4d2765ddad9c4310da

Gladly, the fix already exists using commit b42d1fb9538f680af2f31e864c555414ccba842a which adds support for the statx function.

**Comment by sergiomb2** [comment]
Did the trick 
Thank you
